window.i18n = {
    "appointments": {
        "page_title": "Book an appointment",
        "page_description": "Take part in Baltic brand's launch and discover our exclusive watch models.",
        "setmore": {
            "title": "Try our watches",
            "subtitle": "at our Showroom in Paris",
            "cta": "Schedule an appointment"
        },
        "instagram": {
            "title": "They have already tried our watches",
            "subtitle": "... and here is their feedback",
            "cta": "Discover our watches on Instagram"
        },
        "closed": "Our showroom will be closed until September 1st."
    },
    "landing": {
        "newsletter_tagline": "Subscribe to our emailing list",
        "newsletter_wait": "Subscribing...",
        "newsletter_succeed": "We'll keep you in touch",
        "newsletter_duplicate": "You already subscribed. We'll keep you in touch",
        "newsletter_fail": "Subscription failed. Try again later",
        "baseline": "Baltic, what's next ?",
        "baseline_text": "Our kickstarter is over, thanks to all who participated.<br><br> While awaiting the deliveries, you can pre-order our models on the e-shop that will be launched soon. To keep up-to-date, don\u2019t hesitate to register to our newsletter.<br><br>",
        "newsletter_modale_title": "Don't miss your chance !",
        "newsletter_modale_text": "<p>By subscribing, you will receive exclusive informations about the BALTIC project before anyone else :<br \/> <strong>Date of release, prices, new design, meetings.<\/strong><\/p><br \/><p>This projet needs you to exist and we are sure that you will be happy to contribute and help us to make those watches a success.<\/p>",
        "newsletter_modale_close": "No thanks",
        "introduction_project": "The <strong>Baltic<\/strong> watch project will be released on Kickstarter in mid-2017. Subscribe here to our newsletter and don't miss anything about our watches.",
        "kickwait_days": "before the kickstarter launch",
        "chrono_title": "Chronograph Bicompax 001",
        "chrono_text": "Chronograph with emblematic aspirations.<br \/>With its hand-wound movement, it is a daily pleasure",
        "chrono_specs": "38mm Stainless Steel Case<br \/>Manual Winding ST1901 Movement<br \/>Minimalist dial & leaf hands<br \/> Plexy domed glass<br \/>",
        "three_hands_title": "HMS 001. Automatic",
        "three_hands_text": "Clean and forceful, This three automatic hands fits every opportunity.",
        "three_hands_specs": "38mm Stainless Steel Case<br \/>Automatic Miyota 821A Movement<br \/>Minimalist dial & leaf hands<br \/> Plexy domed glass<br \/>",
        "presentation_adjectives": {
            "refined": "Refined",
            "elegant": "Elegant",
            "timeless": "Timeless",
            "classy": "Classy"
        },
        "presentation_assembled_title": "All our watches are assembled in France",
        "presentation_assembled_text": "All BALTIC Watches are assembled in France.<br \/><br \/>In order to fully-controlled our production process, we have decided to assembled all our watches in France, in the area of Besan\u00e7on.",
        "kickstarter_live_title": "Thanks everyone !",
        "kickstarter_live_text": "The kickstarter campaign is over<br \/><br \/>From <strong>April 12 to May 17<\/strong> our kickstarter campaign <br \/>collected <strong>514 806 \u20ac<\/strong> from <strong>1 044 contributors<\/strong>.",
        "kickstarter_live_button": "Discover on Kickstarter",
        "kickstarter_title": "Launch of our e-shop",
        "kickstarter_text": "Following the success of our campaign, we are going to launch an e-shop to pre-order the watches. Our two models: <strong>chronographs<\/strong> & <strong>three hands<\/strong> will be available before the delivery at the end of the year. <br><br>To keep up-to-date, you can follow us on <a href=\"https:\/\/www.facebook.com\/balticwatches\" target=\"_blank\">Facebook<\/a>, <a href=\"https:\/\/www.instagram.com\/balticwatches\" target=\"_blank\">Instagram<\/a> or suscribe to our mailing-list.",
        "presentation_try_title": "Try our watches",
        "presentation_try_text": "To be able to try all the BALTIC Watches, our Showroom in Paris is open on week days.<br \/><br \/>To book an appointment, you just need to click on the link below and set a date. We will call you back to confirm the appointment a day before.",
        "presentation_try_button": "Schedule an appointment (Paris)",
        "presentation_contact_title": "Inquiries & Orders",
        "presentation_contact_text": "Contact us for any inquiries on this page by tchat and we will answer immediatly or send us an email on <a href=\"mailto:&#99;&#111;&#110;&#116;&#97;ct&#64;&#98;a&#108;t&#105;c-&#119;atc&#104;&#101;&#115;.co&#109;\">&#99;&#111;&#110;&#116;&#97;ct&#64;&#98;a&#108;t&#105;c-&#119;atc&#104;&#101;&#115;.co&#109;<\/a>",
        "presentation_social": "Follow the BALTIC project",
        "facebook_cta": "Stay informed on our Facebook",
        "instagram_cta": "Discover our watches on Instagram"
    },
    "order": {
        "confirmation_title": "Confirmation de votre commande",
        "confirmation_baseline": "Your order is received.",
        "confirmation_card_baseline": "Your card has been charged.",
        "confirmation_back_shop": "Back to the shop",
        "shipping_date": "Shipping : End of 2017",
        "download_button": "Download my invoice",
        "thanks": "Thanks",
        "status": {
            "waiting_payment": "Waiting for payment",
            "payed": "Payed",
            "refunded": "Refunded"
        },
        "vat_included": "VAT included",
        "vat_excluded": "VAT excluded",
        "vat_included_prices": "All prices are VAT included",
        "vat_excluded_prices": "All prices are VAT excluded",
        "cart": {
            "title": "Cart",
            "order_label": "Order",
            "step_cart": "Cart",
            "step_contact": "Contact",
            "step_shipping": "Shipping",
            "step_payment": "Payment",
            "step_confirmation": "Confirmation",
            "shipping": "Express Shipping",
            "shipping_date": "Preorder : shipping end of 2017",
            "shipping_free": "Free",
            "regular_price": "Regular price",
            "price": "Total before shipping",
            "total": "Total",
            "product_number": "Number of products",
            "discount": "Discount",
            "discount_text": "La r\u00e9duction s'applique hors frais de port",
            "back_button": "Back to the shop",
            "checkout_button": "Checkout",
            "confirm_order_button": "Continue with my order",
            "secure_con": "Secure Connection",
            "footer": "",
            "secure_payment_title": "Secure Payment",
            "secure_payment_text": "Transactions made on BALTIC's website are processed by Stripe Inc.",
            "worldwide_shipping_title": "Worldwide express shipping",
            "worldwide_shipping_text": "Worldwide shipping is free for orders over 80,00 \u20ac ",
            "warranty_title": "Returns & Warranty",
            "warranty_text": "Our products are under a 2 years warranty.<br \/>.",
            "form": {
                "contact": "Contact",
                "first_name": "First name",
                "last_name": "Last name",
                "company": "Company",
                "email": "Email",
                "phone": "Phone number",
                "billing_and_shipping": "Billing & Shipping",
                "billing": "Billing",
                "shipping": "Shipping",
                "billing_different": "Billing address is different from shipping address",
                "street": "Street",
                "street_placeholder": "Street, Street Number",
                "indications": "Indications",
                "indications_placeholder": "Appartement, Building, Floor, etc...",
                "city": "City",
                "country": "Country",
                "state": "State \/ Province \/ Region",
                "postcode": "ZIP code \/ state ZIP",
                "button_to_shipping": "Proceed to shipping",
                "button_to_payment": "Proceed to payment",
                "back_to_step": "Back to this step"
            }
        },
        "invoice": {
            "invoice": "Invoice",
            "to": "To",
            "number": "Number",
            "product": "Product",
            "unit_price": "Price (without tax)",
            "quantity": "Quantity",
            "vat": "VAT",
            "total_ht": "Total (without tax)",
            "total_ttc": "Total (with tax)",
            "shipping": "Shipping",
            "free": "Free",
            "website": "https:\/\/baltic-watches.com\/",
            "payed": "Payed",
            "vat_footer": "EU VAT",
            "subtotal_ttc": "Sub-total TTC",
            "coupon_amount": "Discount"
        },
        "tracking": {
            "title": "Order tracking",
            "baseline": "Waiting an order ?",
            "form_title": "Tell us about your order",
            "order_id": "Order number",
            "order_email": "E-mail used for your order",
            "form_button": "Get tracking",
            "form_footer": "All fields marked with an asterisk (*) are mandatory. ",
            "not_found": "Tracking not found, please try again later or contact us",
            "no_tracking": "Your order has been processed. Unfortunately we can't provide you with a tracking number yet."
        },
        "checkout": {
            "charge_success": "Le paiement s'est effecut\u00e9. Redirection vers la page de confirmation...",
            "card_label": "Credit or debit card (+ZIP code)",
            "submit_label": "Pay",
            "exp_label": "Expiration",
            "cvv_label": "Crypto.",
            "aggree": "By placing this order you agree to the",
            "aggree_conditions": "Terms and Conditions.",
            "pay_paypal": "Pay via Paypal"
        },
        "customer_service": {
            "top": "Any question ?",
            "name": "Customer service",
            "title": "How may we assist you ?",
            "banner": "Feel free to contact us",
            "contact_us": "Contact customer service",
            "baseline": "Please fill the form below.",
            "direct": {
                "title": "Direct contact"
            },
            "meet_us": {
                "title": "Meet us",
                "text": "If you are in Paris you can come visit our new showroom by taking an appointment here. You could try all our watches and eventually discover our next project!",
                "button": "Take an appointment"
            },
            "networks": {
                "title": "Social networks",
                "text": "To be sure to get our lastest news, don\u2019t hesitate to follow us on our social media."
            },
            "form": {
                "infos_title": "Your informations",
                "email": "E-mail address",
                "name": "First and last name",
                "phone": "Phone number",
                "demand_title": "Your request",
                "error": "Veuilez remplir tout les champs obligatoire",
                "object": "Object",
                "objects": {
                    "infos_global": "Request for information on a product",
                    "orders_global": "Request about an order",
                    "returns_global": "Return request",
                    "contact_global": "Press\/partnership inquiries",
                    "contact_misc": "Erasing my data"
                },
                "message": "Your message",
                "order_id": "Order number",
                "return_msg": "En cas de retour d\u2019une montre ou d\u2019un accessoire BALTIC, n\u2019h\u00e9sitez pas \u00e0 nous d\u00e9crire le plus pr\u00e9cis\u00e9ment possible les raisons de ce retour dans le champ ci-dessous. (D\u00e9faut, panne, ou autre...)",
                "sent": {
                    "top": "Une confirmation vous a \u00e9t\u00e9 envoy\u00e9e par E-mail",
                    "title": "Request sent",
                    "subtitle": "Merci de votre confiance. Notre \u00e9quipe se charge de r\u00e9pondre au plus vite \u00e0 votre demande."
                }
            }
        }
    },
    "product": {
        "preorder": "Add to cart",
        "free_shipping": "Free shipping",
        "with_st19": "With mecanical movement ST1901",
        "warranty_tagline": "2 years warranty",
        "assembled_in_france": "Assembled in France",
        "infos": "Informations",
        "specifications": "Specifications",
        "movement": "Movement",
        "quantity": "Quantity",
        "strap": "Strap",
        "tax_included": "Tax included",
        "tax_included_text": "Tax included",
        "add_to_cart": "Add to cart",
        "limited_edition": "Limited edition",
        "price_tax_included_text": "Tax included",
        "price_tax_excluded_text": "Tax excluded",
        "in_stock_text": "Shipped within 2 days",
        "out_of_stock_text": "Out of stock - Preorder now",
        "panda_out_of_stock": "Sold out",
        "available_soon": "Available soon",
        "preorder_text": "Preorder",
        "shipping_text": "Free international shipping for orders over 80,00\u20ac",
        "shipping_text_more": "More...",
        "payment_text": "Payments made by ",
        "specs_title": "Technical",
        "specs_subtitle": "specs",
        "specs_question": "A question about our products ? Contact us !",
        "shipping_title": "Shipping",
        "shipping_content": "Tous nos produits sont disponibles en pr\u00e9commande et seront livr\u00e9s fin 2017. <br \/> <br \/> En achetant d\u00e8s maintenant, vous profitez d'un prix r\u00e9duit par rapport au prix final.",
        "suggestions_title": "You may",
        "suggestions_subtitle": "also like",
        "straps": {
            "leather_brown_light": "Lion",
            "leather_brown_dark": "Tobacco",
            "leather_black": "Black",
            "leather_olive": "Olive",
            "leather_desc": "Cuir de veau fran\u00e7ais",
            "perlon_1": "Blue",
            "perlon_2": "Red",
            "perlon_3": "Gray",
            "perlon_4": "Green",
            "leather_sable": "Sable",
            "leather_gray": "Gray",
            "panda_brown_light": "Taupe",
            "panda_brown_dark": "Chocolate",
            "panda_black": "Black"
        },
        "made": {
            "title1": "Assembled",
            "title2": "in France",
            "content": "To provide optimal performances and reliability, we chose to assemble all of our watches in France, near Besan\u00e7on. All components are assembled by hand by qualified watchmakers in order to make a high-quality wristwatch.<br><br>\n        <a href=\"https:\/\/baltic-watches.com\/blog\/how-is-a-baltic-made\">Learn more about how our watches are assembled<\/a>"
        },
        "transparent_case": "Caseback",
        "with_transparent_case": "With transparent caseback",
        "without_transparent_case": "Without transparent caseback",
        "case_bloc": {
            "title": "Open or",
            "subtitle": "closed caseback ?",
            "text": "Every BALTIC watches are sold with a closed caseback with a logo engraved at the center. In option you can select an open caseback that will let you observe the movement inside the watch. Both available for our BICOMPAX 001 & HMS 001, this option comes at a cost of 30\u20ac."
        },
        "panda": {
            "release_date": "AVAILABLE ON 13TH OF JUNE AT 14H00 (UTC+2)",
            "collection_text": "BALTIC is introducing the PANDA and REVERSE PANDA BICOMPAX chronographs in very limited edition.\n        Only 100 pieces for each dial will be available. Inspired by vintage automotive races, our classic BICOMPAX watches gains a touch of sportyness with these two highly contrasted dials for optimum legibility. \n        Three new straps are available for this occasion in black, chocolate brown and taupe grey, with ecru stitching.",
            "description_regular": "The PANDA BICOMPAX chronographs features two black registers \u201cguilloch\u00e9\u201d on a light cream dial. Inspired by vintage automotive races, our classic BICOMPAX gains a touch of sportyness with these two highly contrasted dials for optimum legibility. The indexes and the chapter ring are painted in black. The main hands are black while the registers hands are white. The French words \u201cBicompax Manuel\u201d (Which refers to Manual Winding) are printed in red across the bottom of the dial.",
            "description_reverse": "The REVERSE PANDA BICOMPAX features two textured cream registers on a black dial. Inspired by vintage automotive races, our classic BICOMPAX gains a touch of sportyness with these two highly contrasted dials for optimum legibility. The indexes and chapter ring are painted in cream. The main hands are silver while the registers hands are black. The french words \u00ab Bicompax manuel \u00bb (Which refers to Manual Winding) are printed in white across the bottom of the dial.",
            "limited_edition": "The BALTIC BICOMPAX PANDA and REVERSE PANDA is a very limited edition. Each model will be produced in 100 pieces. A special caseback has been created, engraved with a unique number and a logo in reference to the use of panda chronographs by race car drivers."
        },
        "added_product": "Added product"
    },
    "routes": {
        "home": "\/",
        "shop": "\/shop",
        "appointments": "\/appointments",
        "philosophy": "\/philosophy",
        "product": "\/watches",
        "chronographes": "\/chronographes",
        "three_hands": "\/three-hands",
        "pandas": "\/pandas",
        "press_page": "\/press-page",
        "cart": "\/cart",
        "blog": "\/blog",
        "shipping": "\/shipping",
        "checkout": "\/checkout",
        "landing": "\/landing",
        "order_confirmation": "\/confirmation",
        "order_summary": "\/my_order",
        "terms": "\/terms",
        "invoice": "\/invoice",
        "contact": "\/contact",
        "returns": "\/returns",
        "faqs": "\/faqs",
        "accessories": "\/accessories",
        "accessories_show": "\/accessories",
        "retailers": "\/retailers",
        "one_year": "\/baltic-giveaway",
        "tracking_form": "\/order-tracking",
        "customer_service": "\/contact-service",
        "aquascaphe_landing": "\/aquascaphes\/aquascaphe"
    },
    "site": {
        "email": "E-mail",
        "home_label": "Home",
        "chronograph": "Chronograph",
        "chronograph_col": "The chronographs",
        "three-hands": "Three-hands",
        "three-hands_col": "The three-hands",
        "accessories_col": "Accessories",
        "pandas_col": "The pandas",
        "accessories_subtitle": "Straps and watchroll",
        "vat_included": "VAT included",
        "invoice": "invoice",
        "baltic_collection_nav": "The Baltic collection",
        "cookie-consent": "By using this website you consent to the use of cookies.",
        "not_found": "Page not found",
        "not_found_back": "Back to homepage",
        "banner_kickstarter": "LAUNCH : Support the BALTIC project <a href=\"https:\/\/www.kickstarter.com\/projects\/433151279\/baltic-watches-neo-vintage-watches-assembled-in-fr\/\" targer=\"_blank\">on Kickstarter<\/a> until May 17h !",
        "kickwait_baseline": "Time remaining before the Baltic Kick<span style=\"color:#39ca74\">starter<\/span> campaign",
        "name": "BALTIC Watches",
        "home_title": "Vintage inspired watch brand assembled in France",
        "home_description": "All BALTIC watches are made from a truthfull respect of the vintage watch codes. The output is a real timeless timekeeper. The BALTIC watch project will be released on Kickstarter before mid-2017.<br><br>Your haven\u2019t been selected to won our giveaway? No worries, we kept another surprise for you guys. Be sure to check your email at the end of the giveaway.",
        "home_footer": {
            "social_title": "Social",
            "address_title": "Address",
            "credits_title": "Credits",
            "credits": "Designed in Paris",
            "retailers": "Retailers"
        },
        "menu": {
            "home": "Home",
            "appointments": "Appointments",
            "testimonials": "Testimonials",
            "watches": "Watches",
            "press": "Press",
            "about": "About"
        },
        "social_grid": {
            "title_1": "Baltic's",
            "title_2": "Universe",
            "follow_1": "Follow us",
            "follow_2": "On our Instagram",
            "facebook_1": "Keep in touch",
            "facebook_2": "On Facbeook"
        },
        "blog": {
            "index_title": "Blog",
            "index_description": "",
            "discover": "Discover",
            "newsletter": "Il n'y a pas d'autres articles pour le moment. Inscrivez-vous \u00e0 la newsletter pour \u00eatre tenu inform\u00e9s des publications Baltic.",
            "newsletter_nothing": "Et voil\u00e0 !"
        },
        "one_year": {
            "title": "Today is an important day...",
            "text_1": "A year from now, the april 12th BALTIC was born on <a href=\"https:\/\/www.kickstarter.com\/projects\/433151279\/baltic-watches-neo-vintage-watches-assembled-in-fr?lang=fr\" target=\"_blank\">KICKSTARTER<\/a> through its first hectic day, today we wanted to celebrate this day with you and offer you a giveaway.",
            "text_2": "WHAT HAPPENED IN THIS PAST YEAR\u00a0?",
            "text_3": "We have sold so far thousands of watches and its a trumendous start for us, but its juts a beginning. We want to expand while having in mind our initial idea : make modern watches with vintage horological DNA.<br><br>We found that our passion and taste for these vintage pieces had an echo in what people were looking for and this is great! We already have so much ideas of what we would like to introduce in the future, but we need to remain patient and wait for the prototyping process. trust us! we have some great watches to come.<br><br>Our small team is growing months after months to be able to answer to the growing demand. Your trust makes us strongly beleive in the positive future of BALTIC and we are thrilled of being able to follow our passion.<br><br> In the name of all the people that makes run BALTIC on the day to day, we wanted to thank you !",
            "text_4": "HOW TO WIN TWO BALTIC WATCHES?",
            "text_5": "And it will be one for you, and one for your friend!",
            "text_6": "We have decided to do this giveaway for you and one of your friend! Indeed, we will make you win a BICOMPAX 001 of your choice and a HMS 001 of your choice too.<br><br> To participate to our giveaway, you just have to sign-up on this page with your two correct email address and full name. (Emails has to be different)<br> That\u2019s it! As noted, the giveaway will end april 19TH, 2018 at 11:59 PM (UTC+2).<br><br> Your haven\u2019t been selected to won our giveaway? No worries, we kept another surprise for you guys. Be sure to check your email at the end of the giveaway.",
            "form": {
                "title": "Subscribe giveway form",
                "full_name_1": "Full Name (First Person)",
                "full_name_2": "Full Name (Second Person)",
                "email_1": "Valid Email (First Person)",
                "email_2": "Valid Email (Second Person)",
                "send": "send",
                "confirmation": "Thanks for your participation !",
                "terminated": ""
            },
            "ended": "The giveaway has ended. Results will be announced in a few days. "
        },
        "diver": {
            "title": "Curious about our next watch ?",
            "content": "We are constantly thinking about what is coming next. To be aware of our upcoming watches, the best way is to subscribe to our mailing list."
        },
        "home": {
            "slider_button": "Discover",
            "description": "The BALTIC watches are made for neo-vintage watches enthusiast. <br> We do timeless & traditional watches within the highest modern quality standards.",
            "discover_1": "Discover",
            "discover_2": "The collection",
            "hms": {
                "title_1": "Automatic",
                "title_2": "HMS 001",
                "text": "The HMS 001. is a classy automatic watch inspired from the 1940's step-case watches. This automatic watch is powered by a Miyota 821A in a 38mm 316L stainless steel case with an Italian calf leather strap.",
                "button_1": "Order the",
                "button_2": "HMS 001"
            },
            "bicompax": {
                "title_1": "Chronograph",
                "title_2": "Bicompax 001",
                "text": "The BICOMPAX 001. is a chronograph inspired from the 1940's step-case watches. This mechanical watch is powered by a manual wound ST1901 movement in a 38mm 316L stainless steel case with an Italian calf leather strap.",
                "button_1": "Order the",
                "button_2": "Bicompax 001"
            },
            "made": {
                "title": "All our watches<br \/> are assembled in France",
                "text_title": "L\u2019Atelier BALTIC : An Experienced assembly workshop in France.",
                "text": "We truly think that today we need to act locally. This is why our watches are assembled by hand in France, near Besan\u00e7on, by professional and experienced watchmakers.<br \/><br \/>They will use their expertise to assemble, adjust and test every BALTIC mechanical watch."
            }
        },
        "collection": {
            "hms_description": "The HMS 001. is a classy automatic watch inspired from the 1940's step-case watches. <br \/> This automatic watch is powered by a Miyota 821A in a 38mm 316L stainless steel case with an Italian calf leather strap.",
            "bicompax_description": "The BICOMPAX 001. is a chronograph inspired from the 1940's step-case watches. <br \/> This mechanical watch is powered by a manual wound ST1901 movement in a 38mm 316L stainless steel case with an Italian calf leather strap.",
            "other_hms": "<span class=\"baltic-title\">Discover the other automatic<\/span> <span class=\"baltic-title baltic-title--darker\">HMS 001.<\/span>",
            "other_bicompax": "<span class=\"baltic-title\">Discover the other<\/span> <span class=\"baltic-title baltic-title--darker\">Bicompax 001.<\/span>",
            "other_pandas": "<span class=\"baltic-title\">Discover the other<\/span> <span class=\"baltic-title baltic-title--darker\">Bicompax Pandas.<\/span>"
        },
        "and_you": {
            "description": "We\u2019re impatient to meet you. Reminder; we are located at 20 rue de Maubeuge, 75009 PARIS.<br> Press \u00ab\u00a0P\u00a0\u00bb to enter the first door, then ring at MDB SARL. We are located on the first floor. <br> If you face any problem entering our building please call us at 0181292598"
        },
        "lang_selection_notification": "Vous parlez fran\u00e7ais ? Rendez-vous sur notre site fran\u00e7ais en cliquant sur ce lien.",
        "header": {
            "cart": "cart"
        },
        "press": {
            "page_title": "Baltic in the press",
            "title": "In the press",
            "more_link": "View the article"
        },
        "contact": {
            "contact_label": "Contact",
            "shipping_label": "Shipping",
            "returns_label": "Returns",
            "terms_label": "Terms",
            "faq_label": "Faqs",
            "fullname": "Full name",
            "subject": "Subject",
            "contact_email": "Contact Email",
            "contact_phone": "Contact number",
            "message": "Message",
            "send": "Send",
            "mail_sent": "Message sent"
        },
        "about": {
            "title": "About",
            "promise_1": "The commitment",
            "promise_2": "of BALTIC",
            "birth": "The birth",
            "title_1": "A celebration of traditional watch assembled in France.",
            "text_1": "We are a family of watch connoisseurs with a passion for traditional craftsmanship. We believe the most timeless and desirable watches are often the simplest however, it seems many modern watch brands add unnecessary complexity to their designs. For this reason we decided to create BALTIC. We want to focus on a more authentic approach, bringing together the purest watchmaking techniques to create a vintage-inspired timepiece for your wrist.",
            "text_2": "The results are neo-vintage watches with mechanical movements and well-proportioned cases inspired by the finest vintage watches but within the highest modern quality standards.",
            "text_3": "We truly think that today we need to act locally. This is why our watches are assembled by hand in France, near Besan\u00e7on, by professional and experienced watchmakers.",
            "text_4": "They will use their expertise to assemble, adjust and test every BALTIC mechanical watch."
        }
    },
    "validation": {
        "accepted": "The :attribute must be accepted.",
        "active_url": "The :attribute is not a valid URL.",
        "after": "The :attribute must be a date after :date.",
        "alpha": "The :attribute may only contain letters.",
        "alpha_dash": "The :attribute may only contain letters, numbers, and dashes.",
        "alpha_num": "The :attribute may only contain letters and numbers.",
        "array": "The :attribute must be an array.",
        "before": "The :attribute must be a date before :date.",
        "between": {
            "numeric": "The :attribute must be between :min and :max.",
            "file": "The :attribute must be between :min and :max kilobytes.",
            "string": "The :attribute must be between :min and :max characters.",
            "array": "The :attribute must have between :min and :max items."
        },
        "boolean": "The :attribute field must be true or false.",
        "confirmed": "The :attribute confirmation does not match.",
        "date": "The :attribute is not a valid date.",
        "date_format": "The :attribute does not match the format :format.",
        "different": "The :attribute and :other must be different.",
        "digits": "The :attribute must be :digits digits.",
        "digits_between": "The :attribute must be between :min and :max digits.",
        "dimensions": "The :attribute has invalid image dimensions.",
        "distinct": "The :attribute field has a duplicate value.",
        "email": "The :attribute must be a valid email address.",
        "exists": "The selected :attribute is invalid.",
        "file": "The :attribute must be a file.",
        "filled": "The :attribute field is required.",
        "image": "The :attribute must be an image.",
        "in": "The selected :attribute is invalid.",
        "in_array": "The :attribute field does not exist in :other.",
        "integer": "The :attribute must be an integer.",
        "ip": "The :attribute must be a valid IP address.",
        "json": "The :attribute must be a valid JSON string.",
        "max": {
            "numeric": "The :attribute may not be greater than :max.",
            "file": "The :attribute may not be greater than :max kilobytes.",
            "string": "The :attribute may not be greater than :max characters.",
            "array": "The :attribute may not have more than :max items."
        },
        "mimes": "The :attribute must be a file of type: :values.",
        "mimetypes": "The :attribute must be a file of type: :values.",
        "min": {
            "numeric": "The :attribute must be at least :min.",
            "file": "The :attribute must be at least :min kilobytes.",
            "string": "The :attribute must be at least :min characters.",
            "array": "The :attribute must have at least :min items."
        },
        "not_in": "The selected :attribute is invalid.",
        "numeric": "The :attribute must be a number.",
        "present": "The :attribute field must be present.",
        "regex": "The :attribute format is invalid.",
        "required": "The :attribute field is required.",
        "required_if": "The :attribute field is required when :other is :value.",
        "required_unless": "The :attribute field is required unless :other is in :values.",
        "required_with": "The :attribute field is required when :values is present.",
        "required_with_all": "The :attribute field is required when :values is present.",
        "required_without": "The :attribute field is required when :values is not present.",
        "required_without_all": "The :attribute field is required when none of :values are present.",
        "same": "The :attribute and :other must match.",
        "size": {
            "numeric": "The :attribute must be :size.",
            "file": "The :attribute must be :size kilobytes.",
            "string": "The :attribute must be :size characters.",
            "array": "The :attribute must contain :size items."
        },
        "string": "The :attribute must be a string.",
        "timezone": "The :attribute must be a valid zone.",
        "unique": "The :attribute has already been taken.",
        "uploaded": "The :attribute failed to upload.",
        "url": "The :attribute format is invalid.",
        "custom": {
            "attribute-name": {
                "rule-name": "custom-message"
            }
        },
        "attributes": {
            "customer_email": "email",
            "shipping_first_name": "first name",
            "shipping_last_name": "last name",
            "customer_phone": "phone number"
        }
    },
    "rate": 1.141924027794431
};
